export const FETCH_ASSESSMENTS_REQUEST = 'FETCH_ASSESSMENTS_REQUEST';
export const FETCH_ASSESSMENTS_SUCCESS = 'FETCH_ASSESSMENTS_SUCCESS';
export const FETCH_ASSESSMENTS_FAILURE = 'FETCH_ASSESSMENTS_FAILURE';
export const UPDATE_USER_PERFORMANCE = 'UPDATE_USER_PERFORMANCE';